### ISSUE TITLE
Test hello_socketio Crash

### ISSUE THREAD

**Issue by henry000dev** [shoreditch-ops/artillery-core#115]
I get the following error when trying to run the `hello_socketio.json` example:

```
> artillery run loadtest/hello_socketio.json
Log file: artillery_report_20161124_013708.json
Phase 0 started - duration: 15s
 //usr/local/lib/node_modules/artillery/node_modules/artillery-core/lib/runner.js:281
        return engine.step(rs, scenarioEvents);
                     ^

TypeError: Cannot read property 'step' of undefined
    at /usr/local/lib/node_modules/artillery/node_modules/artillery-core/lib/runner.js:281:22
    at arrayMap (/usr/local/lib/node_modules/artillery/node_modules/artillery-core/node_modules/lodash/index.js:1406:25)
    at Function.map (/usr/local/lib/node_modules/artillery/node_modules/artillery-core/node_modules/lodash/index.js:6710:14)
    at /usr/local/lib/node_modules/artillery/node_modules/artillery-core/lib/runner.js:277:21
    at arrayMap (/usr/local/lib/node_modules/artillery/node_modules/artillery-core/node_modules/lodash/index.js:1406:25)
    at Function.map (/usr/local/lib/node_modules/artillery/node_modules/artillery-core/node_modules/lodash/index.js:6710:14)
    at runScenario (/usr/local/lib/node_modules/artillery/node_modules/artillery-core/lib/runner.js:274:27)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/artillery/node_modules/artillery-core/lib/runner.js:155:5)
    at emitNone (events.js:67:13)
    at EventEmitter.emit (events.js:166:7)
```

I could not see the log file. I am running Node 5.0.0 on Linux SUSE. I am probably missing something.

**Comment by hassy** [comment]
Is that `hello_socketio.json` from the Artillery test suite?

Which version of Artillery is that? `1.5.0-3` or later is needed for Socket.io to work.

**Comment by henry000dev** [comment]
My bad. It turns out I installed an older version of Artillery (not sure why but `npm install -g artillery` gave me an older version). I installed 1.5.0-3 and the problem has gone away.
