### ISSUE TITLE
Crash when reading results after bad http request

### ISSUE THREAD

**Issue by danzel** [shoreditch-ops/artillery-core#96]
I've ran in to a crash, I think it is when the server has a bad return result and I have artillery configured to capture a json variable from the result.

Here are hopefully all of the relevant details.

Stack Trace
```
 |/usr/lib/node_modules/artillery/node_modules/artillery-core/lib/engine_http.js:414
  if (results.length > 1) {
             ^

TypeError: Cannot read property 'length' of undefined
    at extractJSONPath (/usr/lib/node_modules/artillery/node_modules/artillery-core/lib/engine_http.js:414:14)
    at /usr/lib/node_modules/artillery/node_modules/artillery-core/lib/engine_http.js:502:30
    at parseJSON (/usr/lib/node_modules/artillery/node_modules/artillery-core/lib/engine_http.js:404:10)
    at /usr/lib/node_modules/artillery/node_modules/artillery-core/lib/engine_http.js:497:7
    at /usr/lib/node_modules/artillery/node_modules/async/lib/async.js:181:20
    at iterate (/usr/lib/node_modules/artillery/node_modules/async/lib/async.js:262:13)
    at Object.async.forEachOfSeries.async.eachOfSeries (/usr/lib/node_modules/artillery/node_modules/async/lib/async.js:281:9)
    at Object.async.forEachSeries.async.eachSeries (/usr/lib/node_modules/artillery/node_modules/async/lib/async.js:214:22)
    at captureOrMatch (/usr/lib/node_modules/artillery/node_modules/artillery-core/lib/engine_http.js:483:9)
    at done (/usr/lib/node_modules/artillery/node_modules/artillery-core/lib/engine_http.js:239:17)
```

Partial Config
```
"post": {
	"url": "/Player/Register",
	"json": {
		"localPlayerId": "LoadTest",
		"playerName": "LoadTest",
		"lifetimeCookies": 0,
		"showcaseLevel": 0,
		"bakeryLevel": 0
	},
	"capture": {
		"json": "$.UID",
		"as": "UID"
	}
}
```

Source (method stack trace is from)
```
// doc is a JSON object
function extractJSONPath(doc, expr) {
  let results = jsonpath.eval(doc, expr);
  if (results.length > 1) {
    return results[randomInt(0, results.length - 1)];
  } else {
    return results[0];
  }
}
```

Version
```
$ artillery --version
1.5.0-12
```

**Comment by danzel** [comment]
Should be fixed by #93, will reopen otherwise.

**Comment by danzel** [comment]
This was not fixed by #93

**Comment by hassy** [comment]
Thanks for the report @danzel. Looks like it should be straightforward to fix.
